### ISSUE TITLE
Repo not found error

### ISSUE THREAD

**Issue by Era360** [alphaolomi/actions-africastalking#2]
Hello @alphaolomi 
I tried to use this Workflow but I get a repo not found error
![Bug report](https://user-images.githubusercontent.com/76971763/225967730-34e52e4e-c391-4add-af9f-35795a508843.png)

I used `uses: alphaolomi/actions-africastalking-@master`

also tried to use `uses: alphaolomi/action-africastalking-@master` but still the same issue.

**Comment by alphaolomi** [comment]
Fixed on https://github.com/alphaolomi/actions-africastalking/releases/tag/v2.0.0
||
|-| 
|![image](https://user-images.githubusercontent.com/10551599/226112558-3371b0e9-0ef7-4b8e-8612-24692afba2f8.jpeg)|
